USE [master]
GO

/****** Object:  Database [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF]    Script Date: 2014/1/15 12:13:54 ******/
CREATE DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClubWebDB', FILENAME = N'F:\Web\Program\ClubWebDB\ClubWebDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClubWebDB_log', FILENAME = N'F:\Web\Program\ClubWebDB\ClubWebDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [F:\WEB\PROGRAM\CLUBWEBDB\CLUBWEBDB.MDF] SET  READ_WRITE 
GO


